# base image
FROM node:18.14.0-alpine

# set working directory
WORKDIR /app

# copy package.json and package-lock.json to the container
COPY package*.json ./

# install dependencies
RUN npm install --legacy-peer-deps

# copy the rest of the application to the container
COPY . .

# build the application
RUN npm run build

# expose port
EXPOSE 5173

# start the application
CMD ["npm", "start"]
