version: "3.8"
services:
  mongodb:
    image: "mongo"
    volumes:
      - data:/data/db
  api:
    build: ./api
    ports:
      - "8800:8800"
    volumes:
      - logs:/app/logs
      - ./api:/app
      - /app/node_modules
    depends_on:
      - mongodb
  client:
    build: ./client
    ports:
      - "5173:5173"
    volumes:
      - ./client/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - api

  admin:
    build: ./admin
    ports:
      - "5174:5174"
    volumes:
      - ./admin/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - api

volumes:
  data:
  logs: